name: pooja-post

on:
  workflow_dispatch: # Allows manual trigger from GitHub UI and cron-job.org

jobs:
  post-to-instagram:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Auto Post Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }}
        run: python -u main.py
